<header>
    <img src="Image\logo.jpg" alt="Company Logo for Learnova" width="100" style="float: left;">
    <h1>Learnova</h1>
    <h2>Jobs Page</h2>

    <!--Navigation Section-->
    <nav>
        <p class="menu"><a href="index.php">Home</a></p>
        <p class="menu"><a href="jobs.php">Job Positions</a></p>
        <p class="menu"><a href="apply.php">Apply Here</a></p>
        <p class="menu"><a href="about.php">About</a></p>
    </nav>
</header>